### ISSUE TITLE
"unable to open database"

### ISSUE THREAD

**Issue by YDdraigGoch** [weannounce/arrnounced#13]
Hello,
I am trying to use arrnounced with Docker but I get the following error:

> pony.orm.dbapiprovider.OperationalError: unable to open database file

I am not sure how to resolve this.

Thanks in advance

Edit: wanted to add that before this line, there's a lot more python/sqlite error code, I guess related to this. I found this error checking the logs on portainer.

**Comment by weannounce** [comment]
Hi, it's difficult to help you without more information. Could you provide
* complete log, or at the very least the python/sqlite errors you mention
* docker image version
* docker command
* your operating system

In the directory you mapped to `/config`, does it contain the database file (brain.db)?

**Comment by YDdraigGoch** [comment]
I didn't have chance to try sorting this out until now. Sorry that I didn't provide full logs - I'm a muppet for not doing so and not be much of a help.

Anyway, you're quite right it's to do with permissions. I use docker-compose rather than run. Now, even though I use the user flag, or add my user/group to environment, the folders created was still owned by root. I changed the permission to the right username and group and hey ho it works. I say work, but won't be able to try it out until I get a match from a tracker.

Thank you for prompting about permissions.

**Comment by weannounce** [comment]
Great that you found the problem.

Happy IRC'ing.
