### ISSUE TITLE
Can't get to be invited

### ISSUE THREAD

**Issue by rouggy** [weannounce/arrnounced#17]
Hi,

I am really sorry as I feel a bit dumb. I can't find the way to get invited to the channel as I always get a command unknown in the log for my tracker. 
Of course it is just a config error but can't find my answer even by checking the example config. 

If the command to get invited is: /msg BotName identify my_nickname password

What is the correct config for irc_inviter = (I suppose it should be just "BotName" and for irc_invite_cmd = identify my_nickname password 

But this does not work. 

Thanks for help and sorry to bother you for such dumb question

**Comment by weannounce** [comment]
Didn't notice this until now as you closed it.
I hope your issue was resolved. Let me know otherwise.

**Comment by rouggy** [comment]
Yep it was hence I closed. I actually get lots of error messages while connecting to irc thus I thought it was not joining the Chan but it actually did.
