### ISSUE TITLE
Add Tracker

### ISSUE THREAD

**Issue by rouggy** [weannounce/arrnounced#18]
Hello,

Is there a way to add a tracker if I have the *.tracker file but it is not in the autodl-trackers github ?

Thanks

**Comment by weannounce** [comment]
Yeah, absolutely. You just put your .tracker file in the tracker configuration directory. The default path is `~/.arrnounced/autodl-trackers/trackers`. You can also change the directory with the `--trackers` flag when starting Arrnounced.

**Comment by rouggy** [comment]
Thanks a lot and congratulations you made a really good software !
Working very well

**Comment by weannounce** [comment]
Thanks!
