### ISSUE TITLE
Database reduction

### ISSUE THREAD

**Issue by GregTroar** [weannounce/arrnounced#22]
Hi,

Is there a way to reduce the size of the db, in a few months I have snatched around 900,000 releases and db is growing fast.
Any chance to implement an option to keep only xx days in the db ?

I manually deleted in the db as i think there is no other option for now ?

Thanks

**Comment by weannounce** [comment]
You are correct, there is no such functionality at the moment. I want to add it but I have not come up with a good solution for it yet.

It should preferably be something automatic. Perhaps a separate thread, doing maintenance, which triggers once a day or so. Checking for entries that are too old for every received release seems like a waste. Doing it manually in the web UI could be a good complement, but I don't like it as the only way of cleaning old entries.

I'll see what I can do.

**Comment by weannounce** [comment]
Discarding announcements older than X days is now possible. The functionality was added in [0.8.0](https://github.com/weannounce/arrnounced/releases/tag/0.8.0), but there was a performance update to it in [0.8.1](https://github.com/weannounce/arrnounced/releases/tag/0.8.1).

It will by default purge anything older than 365 days. This value can be [changed in the config](https://github.com/weannounce/arrnounced/blob/426e3bc9c16d3ffed48faf9bc9ff36d84927e542/example.toml#L16).

Sorry for the delay in implementing this, I hope it satisfies your needs.

**Comment by GregTroar** [comment]
Hi thanks for this.
I am not using arrnounced anymore as I moved to another project which cover the same needs as what arrnounced is doing
