### ISSUE TITLE
Trackers with multiple announce channels / announcers don't work.

### ISSUE THREAD

**Issue by Cookiezzz** [weannounce/arrnounced#5]
First off, nice work on fixing the repo! I was trying to fix the old repo myself. Managed to make it work with some issues, but my lack of Python knowledge doesn't help.

I'm using IPTorrents as a tracker, and they have multiple announcers / announce channels.
I believe because of that the bot doesn't validate properly if a message should be parsed.

IPTorrents.tracker file.
```

<servers>
		<server
			network="IPTorrents"
			serverNames="irc.iptorrents.com"
			channelNames="#ipt.announce,#ipt.announce2"
			announcerNames="IPT,FunTimes"
		/>
</servers>
```
tracker_config loads channels like this: 
```
def irc_channel(self):
        return self._xml_config.server["channelNames"].lower()
```

The message parser compares it with the channel that a message was sent in.
```
async def on_invite(self, channel, by):
        if channel == self.tracker_config.irc_channel:
            await self.join(self.tracker_config.irc_channel)
            logger.info("%s invited us to join %s", by, channel)
```

So If I'm not mistaken it tries to execute the following:
`if #ipt.announce == #ipt.announce,#ipt.announce2`
Which won't ever be true. I've changed the IPTorrents.tracker file on my system to the following and then it does work.
```

<servers>
		<server
			network="IPTorrents"
			serverNames="irc.iptorrents.com"
			channelNames="#ipt.announce"
			announcerNames="IPT"
		/>
</servers>
```
I'm unsure if there are other sites which have multiple channels and/or announcers. Haven't checked.

**Comment by weannounce** [comment]
Your analysis is correct. I admit I was a bit lazy and just assumed it was always only one channel and announcer.

As I don't use IPTorrent myself could you clarify a few things.
- Arrnounced should join both channels?
- Are there different announcements in the two different channels?
- Is IPT announcing in #ipt.announce and FunTimes announces in #ipt.announce2? Or are they both announcing in both channels or how does it work?

**Comment by Cookiezzz** [comment]
> As I don't use IPTorrent myself could you clarify a few things.
> 
>     * Arrnounced should join both channels?
> 
>     * Are there different announcements in the two different channels?
> 
>     * Is IPT announcing in #ipt.announce and FunTimes announces in #ipt.announce2? Or are they both announcing in both channels or how does it work?

It's not required to have Arrnounced join both channels in my opinion. Both channels do announce exactly the same stuff as far as I can see.
IPT announces in #ipt.announce and Funtimes announces in #ipt.announce2.

**Comment by weannounce** [comment]
Looking at the code for autodl-irssi it looks like the server information in the XML config file is only used to map an incoming IRC message with an announce parser. Which server to connect to and channel to enter is specified in the configuration file equivalent to Arrnounced's settings.cfg.

There are XML tracker files which contains multiple servers, channels and announcer names. I'm leaning towards giving the option to override the servers and the channels in settings.cfg. Or possibly require server and channel to be specified and not use the server info from the XML at all.

**Comment by Cookiezzz** [comment]
Yeah, either of those options would work. I think the latter might be best because when using overrides people tend to forget sometimes. With the latter all irc config is in the settings.cfg file. I only use one tracker so I've changed the .tracker file so for me it's fine now.

**Comment by weannounce** [comment]
I took your advice and made the server, port and channels mandatory in the configuration. I will be testing the pull request for at least a few days before merging. Feel free to do the same and provide input.

**Comment by Cookiezzz** [comment]
Hey, 
Apologies for the delay. I've just updated my setup to use the new files and config. It connected and is suggesting releases fine. Will report back in a couple of days!

**Comment by weannounce** [comment]
No worries. I merged the changes though. If you find any issues or something which can be improved let me know.
