### ISSUE TITLE
 Unable to connect to Sonarr/Radarr

### ISSUE THREAD

**Issue by Cookiezzz** [weannounce/arrnounced#6]
My Sonarr/Radarr instances are behind a reverse proxy with SSL.
When i enter the full URL into settings.cfg it is unable to connect.
If I enter the IP directly with the port and HTTP, it does function.

Config below is unable to connect.
```
[sonarr]
apikey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
url = https://sonarr.mydomain.com

[radarr]
apikey =xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
url = https://radarr.mydomain.com
```

Config below does connect.
```
[sonarr]
apikey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
url = http//x.x.x.x:8989

[radarr]
apikey =xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
url = http//x.x.x.x:7878
```

Not that big of an issue but would prefer to have it working through the proxy. I'll try test some more to track down where the issue might be.

**Comment by weannounce** [comment]
I added Sonarr to my own reverse proxy SSL setup and I see no issue connecting via the proxy. Running Arrnounced with verbose logging (start with -v) and making a phony announcement gives me this.

`2020-02-10 17:12:33,175 - DEBUG:ANNOUNCE_PARSER              - x264: Parsing annoucement '[ New Torrent: The.Incredibly.True.Adventure.of.Two.Girls.in.Love.1995.DVDRip.x264-LGBT | Movies/SD | https://x264.me/details.php?id=13366 | http://www.imdb.com/title/tt0113416/ ]'
2020-02-10 17:12:33,176 - DEBUG:ANNOUNCE_PARSER              - Torrent URL: http://x264.me/download.php/13366/mypasskey/+The.Incredibly.True.Adventure.of.Two.Girls.in.Love.1995.DVDRip.x264-LGBT+.torrent
2020-02-10 17:12:33,176 - INFO:MESSAGE_HANDLER              - Notifying Sonarr of release from x264:  The.Incredibly.True.Adventure.of.Two.Girls.in.Love.1995.DVDRip.x264-LGBT
2020-02-10 17:12:33,234 - DEBUG:urllib3.connectionpool       - Starting new HTTPS connection (1): example.com:443
2020-02-10 17:12:33,780 - DEBUG:urllib3.connectionpool       - https://example.com:443 "POST /api/release/push HTTP/1.1" 200 None
2020-02-10 17:12:33,790 - DEBUG:MESSAGE_HANDLER              - Release was rejected:  The.Incredibly.True.Adventure.of.Two.Girls.in.Love.1995.DVDRip.x264-LGBT
`

Sonarr log:
`20-2-10 17:12:33.5|Info|ReleasePushModule|Release pushed:  The.Incredibly.True.Adventure.of.Two.Girls.in.Love.1995.DVDRip.x264-LGBT  - http://x264.me/download.php/13366/mypasskey/+The.Incredibly.True.Adventure.of.Two.Girls.in.Love.1995.DVDRip.x264-LGBT+.torrent
20-2-10 17:12:33.5|Info|DownloadDecisionMaker|Processing 1 releases
`

Do you get any error message? I pushed an update to master which prints exceptions caught from the request. Do you get any information from that?

**Comment by Cookiezzz** [comment]
I pulled the update from master. It seems to be SSL related but I find that weird as I'm using a valid LE certificate for the reverse proxy.

`HTTPSConnectionPool(host='sonarr.domain.com', port=443): Max retries exceeded with url: /api/release/push (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`

**Comment by weannounce** [comment]
You could try `verify=False` in backend.py just to be sure that's the problem.
```
resp = requests.post(url="{}{}".format(backend['url'], backend['api_path']),
        headers=headers, json=params, verify=False).json()
```
I assume you can access Sonarr/Radarr via the proxy with your web browser.

**Comment by Cookiezzz** [comment]
Yeah, did that. Working now. Seems somehow Python is picky over my SSL cert.. Maybe I'm missing part of the chain or so. In my browser it does work however. Also others apps don't complain. Anyway, I can live with setting verify to false right now. I'll check my certs and figure it out. Thanks for the help on this one!

**Comment by weannounce** [comment]
No problem. Glad it helped
